### ISSUE TITLE
Installation instructions: pip vs. PYTHONPATH

### ISSUE THREAD

**Issue by rjleveque** [clawpack/doc#139]
I did a light edit of the doc pages on installation to suggest pip a bit less strongly than in my last iteration. These are in the PR #138 and visible at:
http://depts.washington.edu/clawpack/v5.4.0alpha/installing.html

This was motivated by running into problems with trying to use `pip install` with some users recently whose gfortran compiler was apparently not compatible for compiling PyClaw.  I will investigate this further and post a separate issue, but my main concern regarding our installation instructions is that when pip fails, it gives non-informative messages and leaves things in a state where the user is not sure where things stand.  In particular, the `site-packages/easy-install.pth` file has not been set to point to this version, so even if non-pyclaw parts of Clawpack are working
fine the import statements won't work.

I think `pip install` is great when it works, and for people who primarily want to use pyclaw and are used to using pip for other Python projects this is probably the way to go.

For other users (e.g. those who only want to use GeoClaw, who I work with a lot), the way pip works can be mysterious and confusing when it fails.

Also, people who have multiple versions of Clawpack and want to switch between them (as we do when validating new results against old versions, or for dual debugging, etc.), I find the approach of setting `PYTHONPATH` appropriately in each shell to work well.  But I know others think there are problems with that approach, so feel free to post about difficulties I may not be aware of.

Some other concerns I have with pip:

 - It adds another dependency, and some people have an out of date pip (or none).

 - Our recommended way to install a particular version requires `git`, adding yet another dependency and layer of mystery for some users, and potential merge conflicts down the road if they edit in place.

In the course of trying to figure out how paths work when both pip and `PYTHONPATH` are used, I created the script `whichclaw.py` in clawpack/clawutil#116 to print out paths and environment variables.. This hasn't been exensively tested, suggestions welcome!

Other opinions on the best way to present our installation options?

**Comment by ketch** [comment]
I think we've completed an iteration of revising this, so I'm closing it.  Please reopen if I'm wrong.
