### ISSUE TITLE
Unlexable setaux file in Geoclaw

### ISSUE THREAD

**Issue by ketch** [clawpack/doc#154]
The page `setaux_defaults.rst` references a setaux file in Geoclaw here:

https://github.com/clawpack/geoclaw/blob/master/src/2d/shallow/setaux.f90

Sphinx complains:

    /Users/ketch/Research/Software/clawpack/doc/doc/setaux_defaults.rst:49: WARNING: Could not lex literal_block as "fortran". Highlighting skipped.

I'm guessing this is because the file in question incorporates fixed-format fortran but has a .f90 extension.  Cleaning up the formatting will probably fix this.

**Comment by mandli** [comment]
I can probably take care of this.

**Comment by mandli** [comment]
Hmm, I cannot reproduce the problem and I also don't see anything egregiously wrong with the file beyond using format line numbers.  Are you seeing this in the build or in the docs themselves?

**Comment by ketch** [comment]
I only see it when I build; it doesn't go into the docs.  The result in the docs is just that this code doesn't get syntax highlighting:

http://www.clawpack.org/setaux_defaults.html

It's not high priority.  You might try updating to the latest release of Sphinx, but if you still can't reproduce it then we shouldn't waste more time on it.

**Comment by mandli** [comment]
See it now (sphinx 1.5.3).  PR at clawpack/geoclaw#248.
