### ISSUE TITLE
Move gallery to separate directory and use intersphinx

### ISSUE THREAD

**Issue by rjleveque** [clawpack/doc#158]
Currently the gallery is generated from code in `doc/doc/gallery` and `doc/doc/pyclaw/gallery` where python scripts create the `.rst` files.

@ketch and I propose creating a new `doc/gallery` directory as a separate Sphinx project with the same templates as the other docs and using [intersphinx](http://www.sphinx-doc.org/en/stable/ext/intersphinx.html) to cross reference pages between them.

Reasons:
 - Using `sphinx-versioning` as suggested in #149 doesn't work well with the current system, since it only sees files that are checked in to the `master` branch of `origin`.  All the gallery files (thumbnails and full simulation results, README's etc.)  are not currently part of `doc/doc` and we don't want to add them.
 - This would simplify building the docs after minor changes since we only need to update the galleries infrequently (e.g. for major releases).  Currently having the gallery files in `doc/doc` discourages people from updating the docs since the galleries can be properly built only if you have run all the examples yourself, and this code is rather fragile.

**Comment by rjleveque** [comment]
@ketch and I started this in #160.

**Comment by ketch** [comment]
This is done.  Closing.
