### ISSUE TITLE
LaTeX on Ruled Rectangles Displaying Incorrectly

### ISSUE THREAD

**Issue by mandli** [clawpack/doc#217]
The docs at https://www.clawpack.org/ruled_rectangles.html do not seem to be rendering at all.  It looks like the tags are ok on a quick glance so I am not sure what is wrong.

**Comment by rjleveque** [comment]
I think I finally figured it out. It displayed fine for me when I navigate there, but not when I followed your link.  The difference is I navigated to http://www.clawpack.org/ruled_rectangles.html and your link uses `https`. Apparently there's a security thing with mathjax, but I fixed it by changing the mathjax link in `conf.py` to also use `https`.
