### ISSUE TITLE
pip installation

### ISSUE THREAD

**Issue by jpw37** [clawpack/doc#220]
I have an active installation of clawpack that I've used quite a bit, but was hoping to use pip to simplify the installation process this time around for some students.  It may be that this issue is with my system, but I thought I would raise it here just in case anyone else runs into something similar.  pip exits with the following error (I only retained the final few lines which seemed to be where the error was)

4 warnings and 1 error generated.
    error: Command "gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch x86_64 -g -I/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/numpy/core/include -I/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/numpy/core/include -I/Library/Frameworks/Python.framework/Versions/3.8/include/python3.8 -I/Library/Frameworks/Python.framework/Versions/3.8/include/python3.8 -c pyclaw/src/pyclaw/limiters/weno/reconstruct.c -o build/temp.macosx-10.9-x86_64-3.8/pyclaw/src/pyclaw/limiters/weno/reconstruct.o -MMD -MF build/temp.macosx-10.9-x86_64-3.8/pyclaw/src/pyclaw/limiters/weno/reconstruct.o.d -std=c99" failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Library/Frameworks/Python.framework/Versions/3.8/bin/python3.8 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/Users/knrider/clawpack_src/clawpack/setup.py'"'"'; __file__='"'"'/Users/knrider/clawpack_src/clawpack/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.

**Comment by mandli** [comment]
This is a bug that sprung up more recently on macOS.  Interestingly it is fixed by modifying the offending code `reconstruct.c` as is done in the PR https://github.com/clawpack/pyclaw/pull/667.  We have not yet merged it yet as this is different from another fix that we have seen although in testing this does seem to fix things.

Just to check though what version of macOS are you running?

**Comment by jpw37** [comment]
I'm running 10.15.7.  I'll try PR#667 and see what happens.  Thanks for the
quick response.

Jared Whitehead
Associate Professor, Mathematics Department
Brigham Young University
350 TMCB, Provo, UT, USA
http://math.byu.edu/~whitehead
http://www.mormon.org/me/15TK

**Comment by mandli** [comment]
Let us know if that works for you.

**Comment by jpw37** [comment]
That worked.  Thanks for the feedback.  Now I'll see if my students can get
through the same process :)

Jared Whitehead
Associate Professor, Mathematics Department
Brigham Young University
350 TMCB, Provo, UT, USA
http://math.byu.edu/~whitehead
http://www.mormon.org/me/15TK

**Comment by mandli** [comment]
Good to know.  Hopefully we can merge this in soon and it won't be an issue.
