### ISSUE TITLE
Applying River Discharge

### ISSUE THREAD

**Issue by sadaf-mahmoudi96** [clawpack/doc#224]
Does anyone know how to apply river discharge (time series or single value) at upstream of a domain? I tried to use set_eta_init.f90, however, the results did not change in comparison with the time I applied no river discharge.

**Comment by mandli** [comment]
I would ask this on [claw-users](https://groups.google.com/u/1/g/claw-users) or at least in GeoClaw raise the issue.  As such I am going to close this issue.

**Comment by rjleveque** [comment]
Sorry for the late reply. It's true that this should eventually be documented in the docs, and it's something I've been meaning to create an example for in GeoClaw first.  I'm going to transfer this issue to GeoClaw to remind me to do so soon.
