### ISSUE TITLE
Document new input parameters

### ISSUE THREAD

**Issue by rjleveque** [clawpack/doc#3]
Many input parameters are gaining more descriptive names and some new ones are being introduced.  Create pages that describe these for classic, amrclaw, pyclaw, geoclaw, etc.

**Comment by rjleveque** [comment]
I think this has mostly been done, but are there specific gaps people know about?

**Comment by mandli** [comment]
Maybe we should do a quick overview of parameters while at SIAM CSE next week although I have a feeling that this could always remain open.

**Comment by ketch** [comment]
I would favor closing it.  If we find specific things that are undocumented, we can open issues for them (or just fix them on the spot).
