### ISSUE TITLE
Write Clawpack 5.x paper

### ISSUE THREAD

**Issue by ketch** [clawpack/doc#77]
The outline is here: https://github.com/clawpack/doc/blob/master/papers/Clawpack5x.md

@ahmadia has volunteered to take the lead on this and we will submit it to [The Journal of Open Research Software (JORS)](http://openresearchsoftware.metajnl.com/).

Author order will be alphabetical, except that @mandli will be first author as credit for leading the writing.

Criteria for authorship:  anyone who has....
- Made a nontrivial contribution to 5.0, 5.1, 5.2,
- Contributes at least a sentence to the paper,
- Has read the final draft and agreed to be an author.

**Comment by mandli** [comment]
Published!
