### ISSUE TITLE
Fix "outputting functionals" section

### ISSUE THREAD

**Issue by mandli** [clawpack/doc#90]
I am not sure if the code itself changed or if the documentation was wrong but as it currently sits the docs for this section are wrong and/or confusing.

**Comment by rjleveque** [comment]
I guess you mean this section?
http://www.clawpack.org/pyclaw/output.html#outputting-functionals

**Comment by mandli** [comment]
That would be the one.  I would have been more specific but I just wanted to remind myself to come back and fix it.

**Comment by ketch** [comment]
It is working in the psystem example, which currently passes on Travis.  What is wrong?

**Comment by mandli** [comment]
I tried to use it the other day and found that the documentation left a lot to be desired for getting going.  For instance the demo uses `state.mf` which should be `state.mF`.  Also it is unclear what exactly the function `compute_f` should do as it sticks things in a capitol `F` array.  Really this would be easy to fix and I intend to go back and make the changes myself, this was more of a reminder to go back and look at it.  I will assign myself.

**Comment by ketch** [comment]
Okay; good points -- and thank you.
